config/routes.rb
Rails.application.routes.draw do
	root 'products#index'
  
  resources :products, only: [:index, :show]
  
  devise_for :users do
	  get '/users/sign_out' => 'devise/sessions#destroy'
	end
	
	get '/shopping_cart' => 'shopping_carts#show', as: 'shopping_cart'
	get '/shopping_cart/add_product/:id' => 'shopping_carts#add_product', as: 'shopping_cart_add_product'
	delete '/shopping_cart/:id' => 'shopping_carts#remove_product', as: 'shopping_cart_remove_product'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	has_and_belongs_to_many_with_deferred_save :products
	belongs_to :user
	validate :product_uniqueness

	def total_price
		products.sum(&:price)
	end

	def add_product product
		products.push product
		save
	end

	def remove_product product
		products.delete product
		save
	end

	private
	def product_uniqueness
		if products.uniq.length < products.length
			errors.add(:products, 'Your cart already contains the product')
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_one :shopping_cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    render template: 'products/show', layout: false
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
	before_action :set_shopping_cart

	def add_product
		current_user.shopping_cart.add_product Product.find(params[:id])
		render 'show'
	end

	def remove_product
		current_user.shopping_cart.remove_product(Product.find params[:id])
		render 'show'
	end

	def show
		
	end

	private
	def set_shopping_cart
		current_user.shopping_cart = ShoppingCart.new unless current_user.shopping_cart.present?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Virtual Shop</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">		        
		        <li><%= link_to 'Home', root_path %></li>		       
		      </ul>
		      
		      <ul class="nav navbar-nav navbar-right">
		      	<% if current_user.present? %>
		      		<li>
		      			<%= link_to shopping_cart_path, class: "btn btn-default" do %>
							    <i class="glyphicon glyphicon-shopping-cart"></i> 
								<% end %>			      		
							</li>	        
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My account <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><%= link_to 'Log out', destroy_user_session_path, method: 'delete' %></li>
			          </ul>
			        </li>
			      <% else %>
			      	<li><%= link_to 'Log in', new_user_session_path %></li>
			      <% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class="row">

<% @products.each do |product| %>
  <div class='col-md-3' >
    <ul class='list-group'>
      <li class='list-group-item product-name'><strong><%= link_to product.name, '#', data: { id: product.id } %></strong></li>
      <li class='list-group-item'><strong>Brand: </strong><%= product.brand %></li>
      <li class='list-group-item'><strong>Model: </strong><%= product.model %></li>
      <li class='list-group-item'><strong>Price: </strong><%= product.price %></li>
    </ul>
  </div>  
<% end %>

<div class='product'></div>

<script>
$('li.product-name').on('click', 'a', function(e){
  e.preventDefault();
  var self = this;
  $.get('/products/' + $(self).data('id')).done(function(data){
    $('.product').html(data);
    $('.modal').modal('show');
  });
});
</script>

app/views/products/show.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= @product.name %></h4>
      </div>
      <div class="modal-body">
        <dl>
          <dt>Brand:</dt>
          <dd class='brand'><%= @product.brand %></dd>
          <dt>Model:</dt>
          <dd class='model'><%= @product.model %></dd>
          <dt>Price:</dt>
          <dd class='price'><%= @product.price %></dd>
          <dt>SKU:</dt>
          <dd class='sku'><%= @product.sku %></dd>
          <dt>Description:</dt>
          <dd class='desc'><%= @product.desc %></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to "Add to cart", shopping_cart_add_product_path(@product), class: "btn btn-primary add-to-cart" if current_user.present?%>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shopping_carts/show.html.erb
<% if current_user.shopping_cart.errors.any? %>
	<div id="error_explanation">
		<p><%= current_user.shopping_cart.errors[:products][0] %></p>
	</div>
<% end %>

<table class="table table-striped">	
	<tr>
		<th>Name</th>
		<th>Brand</th>
		<th>Model</th>
		<th>Price</th>
		<th colspan="1"></th>
	</tr>
	<% current_user.shopping_cart.reload.products.each do |product| %>
		<tr>
			<td><%= product.name %> </td>
			<td><%= product.brand %> </td>
			<td><%= product.model %> </td>
			<td><%= product.price %> </td>
			<td>
				<%= link_to shopping_cart_remove_product_path(product), method: 'delete', class: "btn btn-default" do %>
			    <i class="glyphicon glyphicon-trash"></i> 
				<% end %>
			</td>
		</tr>
	<% end %>
	<tr>
		<td colspan="5"><strong>Total: </strong><%= current_user.shopping_cart.total_price %></td>
	</tr>
</table>